CC	= gcc
CXX	= g++
STRIP	= strip
CFLAGS	= -O2 -I.
LFLAGS	= -pthread

OBJECTS = tools.o convert.o debug.o sockets.o serial.o config.o threads.o sha1.o cccamcrypt.o cccamconn.o cccam-srv.o main.o 

link : $(OBJECTS)
	$(CC) $(LFLAGS) -o twin2cc.x86 $(OBJECTS)
	$(STRIP) twin2cc.x86

.c.o:
	$(CC) -c $(CFLAGS) $< -o $@

clean:
	-rm *.o
	-rm twin2cc.x86
